
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 27
#define YY_END_OF_BUFFER 28
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[329] =
    {   0,
        0,   12,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   28,   26,   24,   26,   26,   11,
       19,   13,   14,   26,   18,   13,   13,   13,   18,   13,
        8,    8,   18,   15,   16,   15,   18,    7,    7,    7,
        7,    7,    7,   26,   14,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,   14,   14,   12,    1,   27,    3,   27,   17,   27,
       27,   11,   19,   13,   14,   27,   18,   13,   13,   18,
       13,    8,    8,   15,   27,   15,   18,    7,    7,    7,
        7,    7,    7,   14,   20,   21,   20,   23,   15,    0,

       10,    0,   11,   16,    0,   10,    0,   13,   18,    9,
       13,    0,    9,    8,    0,    0,    0,    0,    0,    0,
        8,    0,    0,    0,    0,    0,    0,   14,   14,   18,
        7,    0,    0,    7,    7,    7,    7,   25,    7,    4,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    4,    7,    7,    7,    4,    7,    7,    7,    7,
        7,    7,    7,   16,   12,    2,   13,   14,    0,   22,
       23,   10,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    9,    8,    0,    0,
        8,    0,    9,    0,    8,    0,    8,    0,    0,    0,

        0,    0,    7,    7,    7,   25,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    9,    0,    0,    5,    0,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    6,    0,    0,    0,    7,
        7,    7,    7,    7,    7,    7,    7,    7,   10,    0,
        0,   10,    0,    0,    0,    0,    0,    7,    7,    7,

        0,    0,    0,    0,    0,    7,    7,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   31,   31,   33,   34,
       35,   35,   35,   35,   35,   35,   35,   36,   37,   35,
       35,   38,   35,   39,   40,   35,   35,   41,   35,   35,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   35,   57,   58,   59,   60,
       61,   62,   35,   63,   64,   65,   66,   67,   68,   69,
       70,   35,   71,   72,   73,   74,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    5,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    1,    1,    5,    1,    5,    5,    5,
        5,    5,    5,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[341] =
    {   0,
        0,   73,    0,    0,    0,    0,    0,    0,   77,    0,
        0,    0,    0,    0,  794,  795,  150,  766,  149,    0,
      795,  765,  764,  145,  795,  144,  763,  132,  141,  146,
      187,  179,  194,  140,  762,  141,  761,    0,  166,  726,
      169,  723,  168,  782,  757,  118,  720,  123,  730,  118,
      207,  723,  130,  732,  718,  715,  729,  221,  700,  160,
      701,  723,  795,  233,  795,  745,  795,  795,  795,  716,
      211,    0,  795,  795,  795,  180,  795,  725,  709,  239,
      691,    0,  258,  214,  681,  238,  679,    0,  261,  200,
      238,  271,  277,  677,  795,  282,  290,    0,  795,  232,

      695,  332,    0,  795,  260,  689,  399,  672,  296,  295,
      671,  285,  335,  344,  394,  363,  403,  415,  281,  299,
      449,  427,  636,  638,  634,  637,  627,  662,  661,  795,
        0,  290,  301,  240,  629,  626,  618,  321,  632,  267,
      634,  629,  632,  619,  237,  284,  628,  617,  613,  367,
      614,    0,  612,  614,  286,    0,  608,  615,  605,  599,
      612,  602,  614,  795,  357,  795,  795,  795,  404,  795,
        0,  795,  296,  604,  609,  331,  602,  607,  441,  600,
      599,  601,  598,  601,  591,  466,  486,  494,  500,  293,
      433,  508,  527,  350,  531,  330,  357,  594,  593,  587,

      587,  587,  585,  595,  594,  384,  591,  581,  583,  589,
      570,  568,  579,  579,  578,  581,  568,  577,  564,  573,
      563,  556,  555,  551,  558,  560,  556,  376,  398,  575,
      552,  557,  387,  422,  642,  550,  555,  549,  547,  546,
      541,  541,  541,  521,  539,  545,  554,  795,  536,  548,
      536,  548,  532,  539,  531,  538,  531,  534,  543,  527,
      538,  527,  535,  521,  531,  531,  407,  515,  520,  438,
      513,  515,  515,  508,  515,  795,  493,  492,  514,  490,
      494,  474,  478,  477,  469,  478,  475,  464,  432,  457,
      458,  467,  450,  449,  438,  460,  515,  432,  426,  445,

      516,  423,  416,  413,  398,  406,  399,  395,  393,  384,
      369,  371,  361,  329,  328,  328,  318,  288,  266,  268,
      209,  198,  172,  178,  151,  105,   11,  795,  711,  717,
      723,  729,  735,  741,  747,  749,  755,  759,  764,  770
    } ;

static const flex_int16_t yy_def[341] =
    {   0,
      328,    1,  329,  329,  330,  330,  331,  331,  328,    9,
        9,    9,    9,    9,  328,  328,  332,  328,  333,  334,
      328,  328,  328,  335,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  336,  336,  336,
      336,  336,  336,  328,  328,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      333,  334,  328,  328,  328,  335,  328,  328,  328,  328,
      328,   31,  328,  328,  328,  328,  328,  336,  336,  336,
      336,  336,  336,  328,  328,  328,  332,  337,  328,  333,

      328,  328,  334,  328,  335,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  338,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      336,  333,  335,  336,  336,  336,  336,  328,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  328,  328,  328,  328,  328,  328,  328,
      337,  328,  339,  328,  328,  340,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  338,  338,  328,  328,  328,

      328,  328,  336,  336,  336,  328,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  339,  339,  328,
      328,  328,  340,  340,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  339,  328,  328,  340,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  339,  328,
      328,  340,  328,  328,  328,  328,  328,  336,  336,  336,

      328,  328,  328,  328,  328,  336,  336,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,    0,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328
    } ;

static const flex_int16_t yy_nxt[870] =
    {   0,
       16,   16,   17,   16,   18,   19,   20,   21,   22,   23,
       24,   25,   25,   26,   27,   25,   28,   29,   30,   31,
       32,   32,   32,   33,   25,   34,   35,   36,   21,   37,
       38,   38,   38,   39,   38,   40,   38,   41,   42,   43,
       38,   25,   44,   25,   45,   38,   21,   46,   47,   48,
       49,   50,   51,   52,   38,   53,   38,   54,   38,   55,
       56,   57,   58,   38,   59,   43,   38,   60,   38,   61,
       25,   62,   25,   63,   64,  325,   64,   68,   69,   69,
       69,   70,   71,   72,   73,   74,   75,   76,   77,   77,
       78,   74,   77,   79,   80,   81,   82,   83,   83,   83,

       77,   77,   84,   85,   86,   73,   87,   88,   88,   88,
       89,   88,   88,   88,   90,   88,   91,   88,   77,   68,
       77,   75,   88,   73,   88,   88,   88,   88,   88,   92,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   93,
       88,   88,   91,   88,   88,   88,   88,   77,   94,   77,
       75,   96,   97,   96,  101,  106,   98,  108,  104,  109,
      110,  110,  110,  110,  111,  128,   99,   99,  129,  322,
      104,  132,  104,  132,  132,  146,  133,  139,  133,  133,
      143,  140,  152,  144,  120,  141,  147,  107,  153,  152,
      106,  102,  112,  152,  276,  122,  113,  122,  121,  121,

      121,  121,  134,  134,  113,  132,  114,  115,  115,  115,
      133,  117,  132,  135,  161,  162,  101,  133,  116,  117,
      104,  134,  107,  118,  120,  327,  132,  119,  134,  325,
      117,  133,  112,  134,  165,  116,  165,  172,  117,  168,
       99,  248,  123,  132,  134,  132,  124,  118,  133,  125,
      133,  126,  134,  102,  134,  119,  326,  127,  110,  110,
      110,  110,  148,  120,   99,  168,  132,  149,  158,  150,
      172,  133,  159,  134,  102,  113,  132,  121,  121,  121,
      121,  133,  132,  169,  170,  169,  196,  133,   98,  152,
      117,   96,   97,   96,  152,  101,   98,  179,  134,  179,

      186,  229,  107,  120,  188,  115,  115,  115,  134,  117,
      134,  106,  191,  191,  187,  187,  187,  187,  121,  121,
      121,  121,  206,  134,  206,  322,  196,  117,  325,  134,
      207,  180,  102,  134,  100,  328,  208,  100,  230,  213,
      186,  234,  100,  107,  181,  221,  117,  214,  182,  112,
      156,  183,  325,  184,  110,  110,  110,  110,  165,  185,
      165,  113,  196,  114,  115,  115,  115,  117,  190,  195,
      195,  195,  132,  235,  100,  328,  117,  133,  324,  100,
      100,  229,  191,  191,  100,  206,  117,  206,  323,  112,
      322,  100,  174,  322,  100,  117,  100,  234,  100,  189,

      175,  105,  196,  267,  105,  169,  170,  169,  190,  105,
       98,  113,  289,  115,  115,  115,  115,  192,  230,  192,
      194,  321,  193,  193,  193,  193,  117,  217,  122,  235,
      122,  320,  270,  319,  195,  195,  195,  289,  190,  189,
      230,  105,  179,  318,  179,  117,  105,  105,  292,  230,
      317,  105,  191,  191,  120,  316,  152,  152,  105,  177,
      194,  105,  315,  105,  235,  105,  113,  178,  121,  121,
      121,  121,  314,  313,  230,  123,  180,  292,  190,  124,
      235,  117,  125,  312,  126,  187,  187,  187,  187,  181,
      127,  186,  307,  182,  120,  152,  183,  306,  184,  112,

      117,  301,  276,  233,  185,  187,  187,  187,  187,  235,
      233,  113,  228,  188,  115,  115,  115,  228,  117,  115,
      115,  115,  115,  152,  300,  152,  117,  193,  193,  193,
      193,  186,  244,  152,  152,  299,  194,  117,  152,  112,
      245,  245,  245,  245,  244,  117,  245,  245,  245,  245,
      195,  195,  195,  298,  152,  297,  248,  296,  245,  245,
      245,  245,  295,  302,  308,  276,  276,  303,  309,  294,
      304,  310,  244,  293,  291,  290,  194,  228,  305,  311,
      228,  152,  152,  288,  244,  228,  152,  287,  286,  285,
      284,  283,  282,  281,  152,  152,  152,  152,  280,  152,

      279,  278,  248,  276,  277,  276,  275,  274,  273,  105,
      105,  100,  100,  266,  152,  265,  264,  228,  263,  152,
      262,  261,  228,  228,  260,  259,  152,  228,  258,  257,
      152,  152,  256,  255,  228,  268,  254,  228,  253,  228,
      252,  228,  251,  269,  233,  152,  152,  233,  250,  248,
      249,  248,  233,  247,  246,  243,  242,  241,  240,  239,
      238,  237,  236,  232,  231,  227,  226,  225,  152,  224,
      223,  222,  220,  219,  218,  152,  216,  215,  212,  211,
      210,  209,  156,  205,  233,  204,  203,  104,  104,  233,
      233,  202,  201,  200,  233,  199,  198,  104,  104,  176,

      173,  233,  271,  130,  233,  130,  233,   99,  233,  167,
      272,   65,   65,   65,   65,   65,   65,   66,   66,   66,
       66,   66,   66,   67,   67,   67,   67,   67,   67,   95,
       95,   95,   95,   95,   95,  100,  130,  100,  167,  100,
      100,  103,   99,  103,  103,  103,  103,  105,  166,  164,
      105,  105,  105,  131,  131,  171,  163,  171,  171,  171,
      171,  197,  160,  197,  228,  228,  228,  228,  228,  228,
      233,  233,  233,  233,  233,  233,  157,  156,  155,  154,
      151,  145,  142,  104,  138,  137,  136,  130,   99,  104,
      104,  104,   99,  328,   15,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328
    } ;

static const flex_int16_t yy_chk[870] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,  327,    2,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,   17,   17,   17,   19,   24,   17,   26,   28,   28,
       29,   29,   29,   29,   30,   34,   34,   36,   36,  326,
       26,   39,   30,   43,   41,   50,   39,   46,   43,   41,
       48,   46,   53,   48,   32,   46,   50,   24,   53,   53,
       76,   19,   31,   53,  325,   33,   32,   33,   32,   32,

       32,   32,   41,   39,   31,   90,   31,   31,   31,   31,
       90,   32,   51,   39,   60,   60,   71,   51,   31,   31,
       33,   41,   76,   31,   32,  324,   58,   31,   39,  323,
       32,   58,   31,   90,   64,   31,   64,  100,   31,   84,
       84,  322,   33,   91,   51,  134,   33,   31,   91,   33,
      134,   33,   90,   71,   58,   31,  321,   33,   80,   80,
       80,   80,   51,   83,   86,   86,   89,   51,   58,   51,
      105,   89,   58,   58,  100,   83,   92,   83,   83,   83,
       83,   92,   93,   96,   96,   96,  119,   93,   96,  145,
       83,   97,   97,   97,  145,  132,   97,  109,   89,  109,

      110,  173,  105,   83,  112,  112,  112,  112,   92,   83,
       93,  133,  190,  190,  110,  110,  110,  110,  120,  120,
      120,  120,  138,   89,  138,  320,  119,  110,  319,   93,
      140,  109,  132,   92,  102,  196,  140,  102,  173,  146,
      110,  176,  102,  133,  109,  155,  110,  146,  109,  114,
      155,  109,  318,  109,  113,  113,  113,  113,  165,  109,
      165,  114,  197,  114,  114,  114,  114,  113,  116,  194,
      194,  194,  150,  176,  102,  196,  114,  150,  317,  102,
      102,  228,  116,  116,  102,  206,  113,  206,  316,  114,
      315,  102,  102,  314,  102,  114,  102,  233,  102,  115,

      102,  107,  197,  229,  107,  169,  169,  169,  116,  107,
      169,  115,  267,  115,  115,  115,  115,  117,  228,  117,
      118,  313,  117,  117,  117,  117,  115,  150,  122,  233,
      122,  312,  234,  311,  118,  118,  118,  289,  191,  115,
      229,  107,  179,  310,  179,  115,  107,  107,  270,  267,
      309,  107,  191,  191,  121,  308,  307,  306,  107,  107,
      118,  107,  305,  107,  234,  107,  121,  107,  121,  121,
      121,  121,  304,  303,  289,  122,  179,  292,  191,  122,
      270,  121,  122,  302,  122,  186,  186,  186,  186,  179,
      122,  187,  300,  179,  121,  299,  179,  298,  179,  188,

      121,  296,  295,  294,  179,  187,  187,  187,  187,  292,
      293,  188,  291,  188,  188,  188,  188,  290,  187,  189,
      189,  189,  189,  288,  287,  286,  188,  192,  192,  192,
      192,  187,  193,  285,  284,  283,  195,  187,  282,  188,
      244,  244,  244,  244,  245,  188,  193,  193,  193,  193,
      195,  195,  195,  281,  280,  279,  278,  277,  245,  245,
      245,  245,  275,  297,  301,  274,  273,  297,  301,  272,
      297,  301,  193,  271,  269,  268,  195,  230,  297,  301,
      230,  266,  265,  264,  245,  230,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,

      249,  247,  246,  243,  242,  241,  240,  239,  238,  237,
      236,  232,  231,  227,  226,  225,  224,  230,  223,  222,
      221,  220,  230,  230,  219,  218,  217,  230,  216,  215,
      214,  213,  212,  211,  230,  230,  210,  230,  209,  230,
      208,  230,  207,  230,  235,  205,  204,  235,  203,  202,
      201,  200,  235,  199,  198,  185,  184,  183,  182,  181,
      180,  178,  177,  175,  174,  163,  162,  161,  160,  159,
      158,  157,  154,  153,  151,  149,  148,  147,  144,  143,
      142,  141,  139,  137,  235,  136,  135,  129,  128,  235,
      235,  127,  126,  125,  235,  124,  123,  111,  108,  106,

      101,  235,  235,   94,  235,   87,  235,   85,  235,   81,
      235,  329,  329,  329,  329,  329,  329,  330,  330,  330,
      330,  330,  330,  331,  331,  331,  331,  331,  331,  332,
      332,  332,  332,  332,  332,  333,   79,  333,   78,  333,
      333,  334,   70,  334,  334,  334,  334,  335,   66,   62,
      335,  335,  335,  336,  336,  337,   61,  337,  337,  337,
      337,  338,   59,  338,  339,  339,  339,  339,  339,  339,
      340,  340,  340,  340,  340,  340,   57,   56,   55,   54,
       52,   49,   47,   45,   44,   42,   40,   37,   35,   27,
       23,   22,   18,   15,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[28] =
    {   0,
1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
    1, 1, 1, 1, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer_for_parser.l"
#line 4 "lexer_for_parser.l"
    #include<bits/stdc++.h>
    #include <iostream>
    #include <stack>
    #include "data.h"
    #include "data.cpp"
    #include "test.tab.h"
    using namespace std;

    int current_indent = 0;
    stack<int> indent_stack;
    int temp_count=0;

#line 784 "lex.yy.c"

#line 786 "lex.yy.c"

#define INITIAL 0
#define STATE 1
#define DEDENT_STATE 2
#define HELP 3
#define BOX_STATE 4
#define CURLY_STATE 5
#define SMALL_STATE 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 79 "lexer_for_parser.l"


#line 1015 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 329 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 795 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 81 "lexer_for_parser.l"
{
    if(temp_count==0){
        BEGIN(INITIAL);
    }else{
    // cout<<temp_count<<endl;
        unput(yytext[0]);
        temp_count--;
        return DEDENT;
    }
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 93 "lexer_for_parser.l"
{
    BEGIN(INITIAL);
    
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 97 "lexer_for_parser.l"
{
    temp_count--; 
    if(temp_count==0){
        BEGIN(INITIAL);
        }
    else{
            return DEDENT;
            cout<<"spaces already present after newline"<<endl;
            unput(yytext[0]);
    }
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 110 "lexer_for_parser.l"
{ 
    yylval.elem = create_node(1, strdup(yytext));
    yylval.elem->is_terminal = true;
    cout<<"KEYWORD"<<" "<<yytext<<endl; ; 
    string oper = yytext;
    if(oper=="is") return IS;
    else if(oper=="in") return IN;
    else if(oper=="if") return IF;
    else if(oper=="else") {cout<<"else"<<endl;return ELSE; }
    else if(oper=="and") return AND;
    else if(oper=="or") return OR;
    else if(oper=="not") return NOT;
    else if(oper=="yield") return YIELD;
    else if(oper=="from") return FROM;
    else if(oper=="elif") return ELIF;
    else if(oper=="async") return ASYNC;
    else if(oper=="await") return AWAIT;
    else if(oper=="None") return NONE;
    else if(oper=="False") return FALSE;
    else if(oper=="import") return IMPORT;
    else if(oper=="pass") return PASS;
    else if(oper=="break") return BREAK;
    else if(oper=="except") return EXCEPT;
    else if(oper=="raise") return RAISE;
    else if(oper=="True") return TRUE;
    else if(oper=="class") return CLASS;
    else if(oper=="finally") return FINALLY;
    else if(oper=="return") return RETURN;
    else if(oper=="continue") return CONTINUE;
    else if(oper=="for") return FOR;
    else if(oper=="lambda") return LAMBDA;
    else if(oper=="try") return TRY;
    else if(oper=="as") return AS;
    else if(oper=="def") return DEF;
    else if(oper=="nonlocal") return NONLOCAL;
    else if(oper=="while") return WHILE;
    else if(oper=="assert") return ASSERT;
    else if(oper=="del") return DEL;
    else if(oper=="global") return GLOBAL;
    else if(oper=="with") return WITH;
    else if(oper=="None") return NONE;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 153 "lexer_for_parser.l"
{
    yylval.elem = create_node(1, strdup(yytext));
    yylval.elem->is_terminal = true;     
    cout<<"TYPE"<<": "<<yytext<<endl; 
     return TYPE_HINT; 
     }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 160 "lexer_for_parser.l"
{
    yylval.elem = create_node(1, strdup(yytext));
    yylval.elem->is_terminal = true;    
    cout<<"TYPE"<<": "<<yytext<<endl; 
    return FUNC_TYPE_HINT; 
    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 167 "lexer_for_parser.l"
{ 
    yylval.elem = create_node(1, strdup(yytext));
    yylval.elem->is_terminal = true;    
    cout<<"IDENTIFIER"<<" "<<yytext<<endl; 
    return NAME; 
    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 174 "lexer_for_parser.l"
{ 
    yylval.elem = create_node(1, strdup(yytext));
    yylval.elem->is_terminal = true;    
    cout<<"INTEGER"<<" "<<yytext<<endl;
    return INTEGER;
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 180 "lexer_for_parser.l"
{ 
    yylval.elem = create_node(1, strdup(yytext));
    yylval.elem->is_terminal = true;    
    cout<<"FLOAT"<<" "<<yytext<<endl;
    return FLOAT;
    }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 186 "lexer_for_parser.l"
{ 
    yylval.elem = create_node(1, strdup(yytext));
    yylval.elem->is_terminal = true;    
    cout<<"STRING"<<" "<<yytext<<endl;
    return STRING;
    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 192 "lexer_for_parser.l"
{ 
    cout<<"COMMENT"<<" "<<yytext<<endl;
    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 196 "lexer_for_parser.l"
{
            int new_indent = strlen(yytext); 
            if(new_indent%2==1){
                cout<<"ERROR: wrong indentation"<<endl;
                return 0;
            }   
            new_indent = new_indent/2;
            if (new_indent > indent_stack.top()) {
                indent_stack.push( new_indent);
                cout<<"INDENT"<<endl;
                return INDENT;
            }
            else if(new_indent<indent_stack.top()){ 
                while (indent_stack.top()!=0 &&  new_indent < indent_stack.top()) {
                    indent_stack.pop();
                    cout<<"DEDENT"<<endl;
                    temp_count++;
                }
                if(indent_stack.top()!=new_indent){
                    cout<<"ERROR: wrong indentation"<<endl;
                    return 0;
                }
                // temp_count--;
                unput(yytext[0]);
                BEGIN(STATE);
                // return DEDENT;
                // cout<<"DEDENT"<<endl;
                // return DEDENT;
            }
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 229 "lexer_for_parser.l"
{ 
    yylval.elem = create_node(1, strdup(yytext));
    yylval.elem->is_terminal = true;    
    string oper = yytext;
    if(oper=="**") return POW;
    else if(oper=="//") return FLOOR_DIV;
    else if(oper=="/") return DIV;
    else if(oper=="*") return MUL;
    else if(oper=="+") return ADD;
    else if(oper=="-") return SUB;
    else if(oper=="%") return MOD;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 242 "lexer_for_parser.l"
{ 
    yylval.elem = create_node(1, strdup(yytext));
    yylval.elem->is_terminal = true;    
    string oper = yytext;
    if(oper=="<<") return SHIFT_LEFT;
    else if(oper==">>") return SHIFT_RIGHT;
    else if(oper=="&") return BITWISE_AND;
    else if(oper=="|") return BITWISE_OR;
    else if(oper=="^") return BITWISE_XOR;
    else if(oper=="~") {
        cout<<"sending ~"<<endl;
        return TILDE;
    }
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 257 "lexer_for_parser.l"
{
    yylval.elem = create_node(1, strdup(yytext));
    yylval.elem->is_terminal = true;    
    string oper = yytext;
    if(oper=="==") return DOUBLE_EQUAL;
    else if(oper=="!=") return NE;
    else if(oper==">") return GT;
    else if(oper=="<") return LT;
    else if(oper==">=") return GE;
    else if(oper=="<=") return LE;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 269 "lexer_for_parser.l"
{
    yylval.elem = create_node(1, strdup(yytext));
    yylval.elem->is_terminal = true;
    string oper = yytext;
    if(oper==":=") return WAL_OP;
    else if(oper=="=") return EQUAL;
    else if(oper=="+=") return ADD_EQUAL;
    else if(oper=="-=") return SUB_EQUAL;
    else if(oper=="*=") return MUL_EQUAL;
    else if(oper=="/=") return DIV_EQUAL;
    else if(oper=="%=") return MOD_EQUAL;
    else if(oper=="**=") return POW_EQUAL;
    else if(oper=="&=") return BITWISE_AND_EQUAL;
    else if(oper=="|=") return BITWISE_OR_EQUAL;
    else if(oper=="^=") return BITWISE_XOR_EQUAL;
    else if(oper=="<<=") return SHIFT_LEFT_EQUAL;
    else if(oper==">>=") return SHIFT_RIGHT_EQUAL;
    else if(oper=="//=") return FLOOR_DIV_EQUAL;

}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 290 "lexer_for_parser.l"
{
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 294 "lexer_for_parser.l"
{ 
    yylval.elem = create_node(1, strdup(yytext));
    yylval.elem->is_terminal = true;
    cout<<"DELIMITER"<<" "<<yytext<<endl;
    string oper = yytext;

    if(oper=="@") return AT;
    else if(oper==",") return COMMA;
    else if(oper==":") return COLON;
    else if(oper=="(") {BEGIN(SMALL_STATE);return SMALL_OPEN;}
    else if(oper==")") {BEGIN(INITIAL);return SMALL_CLOSE;}
    else if(oper=="[") { BEGIN(BOX_STATE);return BOX_OPEN;}
    else if(oper=="]") { BEGIN(INITIAL);return BOX_CLOSE;}
    else if(oper=="{") {BEGIN(CURLY_STATE);return CURLY_OPEN;}
    else if(oper=="}") {BEGIN(INITIAL);return CURLY_CLOSE;}
    else if(oper==".") return DOT;
    else if(oper=="->") return ARROW;
    
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 314 "lexer_for_parser.l"
{
    cout<<"Error: Unexpected character "<<yytext<< " at line "<<yylineno<< endl;
    return 0;
}
	YY_BREAK
case 20:
/* rule 20 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 320 "lexer_for_parser.l"
{
      while (indent_stack.top()!=0) {
            indent_stack.pop();
            cout<<"DEDENT"<<endl;
            temp_count++;
        }
        if(indent_stack.top()!=0){
            cout<<"ERROR: wrong indentation"<<endl;
            return 0;
        }
        // temp_count--;
        unput(yytext[0]);
        BEGIN(STATE);
        cout<<"NEWLINE"<<endl; 
        return NEWLINE ;
    }
	YY_BREAK
/*^[ \t]*{COMMENT}?"\n" {
        //ignore empty lines and lines only with comment
    }*/
case 21:
/* rule 21 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 342 "lexer_for_parser.l"
{
    cout<<"NEWLINE"<<endl;
    return NEWLINE;
}
	YY_BREAK
case 22:
/* rule 22 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 347 "lexer_for_parser.l"
{
    cout<<"EMpty line";
}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 351 "lexer_for_parser.l"
{
    cout<<"comment detected"<<endl;
}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 355 "lexer_for_parser.l"
{
     while (indent_stack.top()!=0) {
            indent_stack.pop();
            cout<<"DEDENT"<<endl;
            temp_count++;
        }
        if(indent_stack.top()!=0){
            cout<<"ERROR: wrong indentation"<<endl;
            return 0;
        }
        // temp_count--;
        unput(yytext[0]);
        BEGIN(STATE);
        cout<<"Last NEWLINE"<<endl; 
        return NEWLINE ;
        // this will only when the last is newline not followed by spaces and tabs

}
	YY_BREAK
/*explicit line joining*/
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 374 "lexer_for_parser.l"
{}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 375 "lexer_for_parser.l"
{ }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 376 "lexer_for_parser.l"
ECHO;
	YY_BREAK
#line 1487 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STATE):
case YY_STATE_EOF(DEDENT_STATE):
case YY_STATE_EOF(HELP):
case YY_STATE_EOF(BOX_STATE):
case YY_STATE_EOF(CURLY_STATE):
case YY_STATE_EOF(SMALL_STATE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 329 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 329 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 328);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 376 "lexer_for_parser.l"


// int main(){
//     indent_stack.push(0);

//     yylex();
//     return 0;
// }

